# Generated by Django 5.2.7 on 2025-12-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0004_fieldgroup_alter_fieldvalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='group_name',
        ),
        migrations.AddField(
            model_name='field',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='document_automation.fieldgroup', verbose_name='Nhóm'),
        ),
    ]
