# Generated by Django 5.2.7 on 2025-12-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0007_alter_fieldgroup_options_alter_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cccd_so',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name_for_display',
        ),
    ]
