# Generated by Django 5.2.7 on 2025-12-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0008_remove_person_cccd_so_remove_person_name_for_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên vai trò')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vai trò (Role)',
                'verbose_name_plural': 'Quản lý Vai trò',
            },
        ),
    ]
