# Generated by Django 5.2.7 on 2025-12-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0009_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS Class tùy chỉnh'),
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='field',
            name='width_cols',
            field=models.IntegerField(default=12, verbose_name='Độ rộng (1-12)'),
        ),
    ]
