# Generated by Django 5.2.7 on 2025-12-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0010_field_css_class_field_order_field_width_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tài sản',
                'verbose_name_plural': 'Tài sản',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.asset'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('loan_profile', 'person', 'asset', 'field')},
        ),
        migrations.CreateModel(
            name='LoanProfileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_profiles', to='document_automation.asset')),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_assets', to='document_automation.loanprofile')),
            ],
            options={
                'verbose_name': 'Liên kết Hồ sơ và Tài sản',
                'verbose_name_plural': 'Liên kết Hồ sơ và Tài sản',
                'unique_together': {('loan_profile', 'asset')},
            },
        ),
    ]
