# Generated by Django 5.2.7 on 2025-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0012_add_is_protected_to_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default_value',
            field=models.TextField(blank=True, null=True, verbose_name='Giá trị mặc định'),
        ),
    ]
