# Generated by Django 5.2.7 on 2025-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0013_add_default_value_to_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Văn bản'), ('TEXTAREA', 'Đoạn văn bản'), ('NUMBER', 'Số'), ('DATE', 'Ngày'), ('CHECKBOX', 'Hộp kiểm')], default='TEXT', max_length=50, verbose_name='Loại dữ liệu'),
        ),
    ]
