# Generated by Django 5.2.7 on 2025-12-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0015_formview_field_allowed_forms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='form_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_automation.formview', verbose_name='Cấu hình Form'),
        ),
    ]
