# Generated by Django 5.2.7 on 2025-12-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0021_asset_last_updated_by_person_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='entity_type',
            field=models.CharField(choices=[('PROFILE', 'Hồ sơ'), ('PERSON', 'Cá nhân'), ('ASSET', 'Tài sản'), ('SAVINGS', 'Sổ tiết kiệm')], default='PROFILE', max_length=20, verbose_name='Đối tượng áp dụng'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='loan_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.loanprofile'),
        ),
    ]
