# Generated by Django 5.2.7 on 2025-11-11 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nhãn hiển thị')),
                ('placeholder_key', models.CharField(max_length=100, unique=True, verbose_name='Tên định danh')),
                ('data_type', models.CharField(choices=[('TEXT', 'Văn bản'), ('NUMBER', 'Số'), ('DATE', 'Ngày'), ('CHOICE', 'Lựa chọn (Dropdown)'), ('CHECKBOX', 'Hộp kiểm')], default='TEXT', max_length=50, verbose_name='Loại dữ liệu')),
                ('group_name', models.CharField(choices=[('KHOAN_VAY', 'Thông tin Khoản vay'), ('KHACH_HANG', 'Thông tin Khách hàng'), ('TSBD', 'Thông tin Tài sản bảo đảm'), ('NGUOI_LIEN_QUAN', 'Thông tin Người liên quan')], max_length=100, verbose_name='Nhóm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Trường Dữ liệu',
                'verbose_name_plural': 'Trường Dữ liệu',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_display', models.CharField(default='Người liên quan', max_length=255, verbose_name='Tên hiển thị')),
            ],
            options={
                'verbose_name': 'Người Liên quan',
                'verbose_name_plural': 'Người Liên quan',
            },
        ),
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('name', models.CharField(default='Hồ sơ vay mới', max_length=255, verbose_name='Tên hồ sơ')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Hồ sơ Vay',
                'verbose_name_plural': 'Hồ sơ Vay',
            },
        ),
        migrations.CreateModel(
            name='LoanProfilePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list, verbose_name='Vai trò')),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.loanprofile', verbose_name='Hồ sơ vay')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.person', verbose_name='Người liên quan')),
            ],
            options={
                'verbose_name': 'Liên kết Hồ sơ và Người',
                'verbose_name_plural': 'Liên kết Hồ sơ và Người',
                'unique_together': {('loan_profile', 'person')},
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Giá trị')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.field', verbose_name='Trường')),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.loanprofile', verbose_name='Hồ sơ vay')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.person', verbose_name='Người liên quan')),
            ],
            options={
                'verbose_name': 'Giá trị Trường',
                'verbose_name_plural': 'Giá trị Trường',
                'unique_together': {('loan_profile', 'person', 'field')},
            },
        ),
    ]
