# Generated by Django 5.2.7 on 2025-12-31 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('file', models.FileField(upload_to='doc_templates/', verbose_name='File mẫu (.docx)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': 'Mẫu Tài liệu',
                'verbose_name_plural': 'Mẫu Tài liệu',
            },
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('entity_type', models.CharField(choices=[('PROFILE', 'Hồ sơ'), ('PERSON', 'Cá nhân'), ('ASSET', 'Tài sản'), ('SAVINGS', 'Sổ tiết kiệm')], default='PROFILE', max_length=20, verbose_name='Đối tượng áp dụng')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Nhóm Trường',
                'verbose_name_plural': 'Nhóm Trường',
            },
        ),
        migrations.CreateModel(
            name='FormView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Form')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Mã định danh (Slug)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Cấu hình Form',
                'verbose_name_plural': 'Cấu hình Form',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên vai trò')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã định danh (Slug)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vai trò (Role)',
                'verbose_name_plural': 'Quản lý Vai trò',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nhãn hiển thị')),
                ('placeholder_key', models.CharField(max_length=100, unique=True, verbose_name='Tên định danh (Key)')),
                ('data_type', models.CharField(choices=[('TEXT', 'Văn bản'), ('TEXTAREA', 'Đoạn văn bản'), ('NUMBER', 'Số'), ('DATE', 'Ngày'), ('CHECKBOX', 'Hộp kiểm')], default='TEXT', max_length=50, verbose_name='Loại dữ liệu')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('width_cols', models.IntegerField(default=12, verbose_name='Độ rộng (1-12)')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS Class tùy chỉnh')),
                ('is_active', models.BooleanField(default=True)),
                ('is_protected', models.BooleanField(default=False, verbose_name='Được bảo vệ (không xóa được)')),
                ('use_digit_grouping', models.BooleanField(default=False, verbose_name='Phân tách hàng nghìn (chuẩn vi-VN)')),
                ('show_amount_in_words', models.BooleanField(default=False, verbose_name='Hiển thị số thành chữ (Frontend)')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='Giá trị mặc định')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='document_automation.fieldgroup', verbose_name='Nhóm')),
                ('allowed_forms', models.ManyToManyField(blank=True, related_name='fields', to='document_automation.formview', verbose_name='Hiển thị ở Form')),
            ],
            options={
                'verbose_name': 'Trường Dữ liệu',
                'verbose_name_plural': 'Trường Dữ liệu',
            },
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='allowed_forms',
            field=models.ManyToManyField(blank=True, related_name='groups', to='document_automation.formview', verbose_name='Hiển thị ở Form'),
        ),
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Hồ sơ mới', max_length=255, verbose_name='Tên hồ sơ')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_automation.formview', verbose_name='Cấu hình Form')),
            ],
            options={
                'verbose_name': 'Hồ sơ Vay',
                'verbose_name_plural': 'Hồ sơ Vay',
            },
        ),
        migrations.CreateModel(
            name='MasterObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('PERSON', 'Cá nhân'), ('ASSET', 'Tài sản'), ('SAVINGS', 'Sổ tiết kiệm'), ('VEHICLE', 'Phương tiện'), ('INSURANCE', 'Bảo hiểm'), ('BOND', 'Trái phiếu')], max_length=20, verbose_name='Loại đối tượng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Đối tượng',
                'verbose_name_plural': 'Các đối tượng',
            },
        ),
        migrations.CreateModel(
            name='LoanProfileObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, verbose_name='Vai trò')),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='document_automation.loanprofile')),
                ('master_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='document_automation.masterobject')),
            ],
            options={
                'verbose_name': 'Liên kết Hồ sơ và Đối tượng',
                'verbose_name_plural': 'Liên kết Hồ sơ và Đối tượng',
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Giá trị thực tế')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.field', verbose_name='Trường')),
                ('loan_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.loanprofile', verbose_name='Hồ sơ')),
                ('master_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.masterobject', verbose_name='Đối tượng')),
            ],
            options={
                'verbose_name': 'Giá trị',
                'verbose_name_plural': 'Các giá trị',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú về nhân sự')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='masterobject',
            index=models.Index(fields=['object_type'], name='document_au_object__e5b02f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanprofileobjectlink',
            index=models.Index(fields=['loan_profile', 'master_object'], name='document_au_loan_pr_d0de07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanprofileobjectlink',
            unique_together={('loan_profile', 'master_object')},
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['loan_profile'], name='document_au_loan_pr_b3ee3f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['master_object'], name='document_au_master__15c625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('loan_profile', 'master_object', 'field')},
        ),
    ]
