# Generated by Django 5.2.7 on 2025-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã loại (VD: PERSON)')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị (VD: Cá nhân)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_system', models.BooleanField(default=False, verbose_name='Là hệ thống (Không xóa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại Đối tượng',
                'verbose_name_plural': 'Các Loại Đối tượng',
            },
        ),
        migrations.AlterField(
            model_name='masterobject',
            name='object_type',
            field=models.CharField(max_length=20, verbose_name='Loại đối tượng'),
        ),
    ]
