# Generated by Django 5.2.7 on 2025-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('file', models.FileField(upload_to='doc_templates/', verbose_name='File mẫu (.docx)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': 'Mẫu Tài liệu',
                'verbose_name_plural': 'Mẫu Tài liệu',
            },
        ),
    ]
