# Generated by Django 5.2.7 on 2025-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0002_masterobjecttype_alter_masterobject_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã định danh (Slug)'),
        ),
    ]
