# Generated by Django 5.2.7 on 2025-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0002_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cccd_so',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CCCD'),
        ),
    ]
