# Generated by Django 5.2.7 on 2025-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0003_fieldgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='layout_position',
            field=models.CharField(choices=[('LEFT', 'Cột Trái'), ('RIGHT', 'Cột Phải')], default='LEFT', max_length=10, verbose_name='Vị trí hiển thị'),
        ),
    ]
