# Generated by Django 5.2.7 on 2025-12-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0003_person_cccd_so'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fieldvalue',
            options={'verbose_name': 'Giá trị', 'verbose_name_plural': 'Các giá trị'},
        ),
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Văn bản'), ('NUMBER', 'Số'), ('DATE', 'Ngày'), ('CHECKBOX', 'Hộp kiểm')], default='TEXT', max_length=50, verbose_name='Loại dữ liệu'),
        ),
        migrations.AlterField(
            model_name='field',
            name='group_name',
            field=models.CharField(choices=[('KHOAN_VAY', 'Thông tin Khoản vay'), ('KHACH_HANG', 'Thông tin Khách hàng'), ('TSBD', 'Thông tin Tài sản bảo đảm'), ('KHAC', 'Thông tin Khác')], max_length=100, verbose_name='Nhóm'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder_key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên định danh (Key)'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.field'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='loan_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_automation.loanprofile'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document_automation.person'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='value',
            field=models.TextField(verbose_name='Giá trị thực tế'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='name',
            field=models.CharField(default='Hồ sơ mới', max_length=255, verbose_name='Tên hồ sơ'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanprofileperson',
            name='loan_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_people', to='document_automation.loanprofile'),
        ),
        migrations.AlterField(
            model_name='loanprofileperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_profiles', to='document_automation.person'),
        ),
        migrations.AlterField(
            model_name='loanprofileperson',
            name='roles',
            field=models.JSONField(default=list, verbose_name='Danh sách vai trò'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_for_display',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
    ]
