# Generated by Django 5.2.7 on 2026-01-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0004_fieldgroup_layout_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='allowed_object_types',
            field=models.ManyToManyField(blank=True, related_name='fields', to='document_automation.masterobjecttype', verbose_name='Loại Đối tượng áp dụng'),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='allowed_object_types',
            field=models.ManyToManyField(blank=True, related_name='groups', to='document_automation.masterobjecttype', verbose_name='Loại Đối tượng áp dụng'),
        ),
    ]
