# Generated by Django 5.2.7 on 2026-01-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0005_field_allowed_object_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='object_type',
            field=models.ForeignKey(blank=True, help_text='Nhóm này dành cho loại đối tượng nào? Để trống = Thông tin chung (CORE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorized_groups', to='document_automation.masterobjecttype', verbose_name='Phân loại nhóm'),
        ),
    ]
