# Generated by Django 5.2.7 on 2025-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0006_field_note_fieldgroup_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldgroup',
            options={'verbose_name': 'Nhóm Trường', 'verbose_name_plural': 'Nhóm Trường'},
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
