# Generated by Django 5.2.7 on 2026-01-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0006_fieldgroup_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='identity_field_key',
            field=models.CharField(blank=True, help_text='Placeholder key của trường dùng để làm tên định danh (VD: ho_ten, bien_so_xe)', max_length=100, null=True, verbose_name='Trường định danh (key)'),
        ),
    ]
