# Generated by Django 5.2.7 on 2026-01-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0007_masterobjecttype_identity_field_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Role quan trọng không được phép xóa', verbose_name='Là hệ thống'),
        ),
        migrations.AddField(
            model_name='role',
            name='relation_type',
            field=models.CharField(blank=True, help_text='Nếu Role này được chọn, hệ thống sẽ tự động gán quan hệ này (VD: OWNER)', max_length=50, null=True, verbose_name='Loại quan hệ tự động'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MasterObjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50, verbose_name='Loại quan hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_source', to='document_automation.masterobject', verbose_name='Đối tượng nguồn')),
                ('target_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_target', to='document_automation.masterobject', verbose_name='Đối tượng đích')),
            ],
            options={
                'verbose_name': 'Quan hệ Đối tượng',
                'verbose_name_plural': 'Quan hệ Đối tượng',
                'indexes': [models.Index(fields=['source_object'], name='document_au_source__31ea25_idx'), models.Index(fields=['target_object'], name='document_au_target__bf07a9_idx')],
                'unique_together': {('source_object', 'target_object', 'relation_type')},
            },
        ),
    ]
