# Generated by Django 5.2.7 on 2026-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0008_role_is_system_role_relation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='lock_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu khóa (Dev)'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Đang xử lý (Nháp)'), ('FINALIZED', 'Đã hoàn tất (Khóa)')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
