# Generated by Django 5.2.7 on 2026-01-14 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0009_loanprofile_lock_password_loanprofile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi làm việc/Phòng ban'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa')], max_length=20, verbose_name='Hành động')),
                ('target_model', models.CharField(max_length=100, verbose_name='Đối tượng tác động')),
                ('target_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID đối tượng')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Chi tiết thay đổi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký tác động',
                'verbose_name_plural': 'Nhật ký tác động',
                'ordering': ['-timestamp'],
            },
        ),
    ]
