# Generated by Django 5.2.7 on 2026-01-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0010_userprofile_full_name_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi làm việc'),
        ),
    ]
