# Generated by Django 5.2.7 on 2026-01-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0011_userprofile_department_alter_userprofile_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='ui_display',
            field=models.CharField(choices=[('SECTION', 'Standalone Section (như Đại diện Ngân hàng)'), ('LIST', 'Mục trong danh sách tổng hợp (như Tài sản)'), ('HIDDEN', 'Ẩn khỏi giao diện nhập liệu')], default='LIST', max_length=20, verbose_name='Cách hiển thị UI'),
        ),
        migrations.AddField(
            model_name='masterobjecttype',
            name='ui_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon (Emoji hoặc SVG class)'),
        ),
    ]
