# Generated by Django 5.2.7 on 2025-12-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0011_asset_alter_fieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='Được bảo vệ (không xóa được)'),
        ),
    ]
