# Generated by Django 5.2.7 on 2026-01-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0012_masterobjecttype_ui_display_masterobjecttype_ui_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterobjecttype',
            name='ui_display',
        ),
        migrations.RemoveField(
            model_name='masterobjecttype',
            name='ui_icon',
        ),
        migrations.AddField(
            model_name='masterobjecttype',
            name='form_display_mode',
            field=models.CharField(choices=[('ASSET_LIST', 'Gom trong danh sách Tài sản'), ('DEDICATED_SECTION', 'Hiển thị khu vực riêng')], default='ASSET_LIST', help_text='Chọn cách đối tượng này hiển thị trong hồ sơ vay', max_length=30, verbose_name='Chế độ hiển thị Form'),
        ),
    ]
