# Generated by Django 5.2.7 on 2026-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0013_remove_masterobjecttype_ui_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='dynamic_summary_template',
            field=models.CharField(blank=True, help_text='Mẫu để hiển thị thông tin bổ sung (VD: CCCD: {cccd})', max_length=255, null=True, verbose_name='Mẫu hiển thị tóm tắt'),
        ),
    ]
