# Generated by Django 5.2.7 on 2026-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0014_masterobjecttype_dynamic_summary_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bộ phận'),
        ),
    ]
