# Generated by Django 5.2.7 on 2025-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0014_alter_field_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Form')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Mã định danh (Slug)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Cấu hình Form',
                'verbose_name_plural': 'Cấu hình Form',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='allowed_forms',
            field=models.ManyToManyField(blank=True, related_name='fields', to='document_automation.formview', verbose_name='Hiển thị ở Form'),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='allowed_forms',
            field=models.ManyToManyField(blank=True, related_name='groups', to='document_automation.formview', verbose_name='Hiển thị ở Form'),
        ),
    ]
