# Generated by Django 5.2.7 on 2026-01-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0015_documenttemplate_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
    ]
