# Generated by Django 5.2.7 on 2026-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0016_masterobjecttype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='layout_position',
            field=models.CharField(choices=[('LEFT', 'Cột Trái'), ('RIGHT', 'Cột Phải')], default='LEFT', max_length=10, verbose_name='Vị trí hiển thị'),
        ),
    ]
