# Generated by Django 5.2.7 on 2025-12-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0016_loanprofile_form_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã định danh (Slug)'),
        ),
    ]
