# Generated by Django 5.2.7 on 2025-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0017_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='use_digit_grouping',
            field=models.BooleanField(default=False, verbose_name='Phân tách hàng nghìn (chuẩn vi-VN)'),
        ),
    ]
