# Generated by Django 5.2.7 on 2026-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0017_masterobjecttype_layout_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='allow_relations',
            field=models.BooleanField(default=True, help_text='Nếu tắt, đối tượng này sẽ không hiển thị phần gán quan hệ và không thể được chọn làm đích liên kết.', verbose_name='Cho phép liên kết'),
        ),
    ]
