# Generated by Django 5.2.7 on 2026-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0018_masterobjecttype_allow_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterobjecttype',
            name='allow_relations',
            field=models.BooleanField(default=True, help_text="Nếu tắt, đối tượng này sẽ không xuất hiện trong danh sách gán quan hệ và không hiển thị khu vực 'Các liên kết liên quan'", verbose_name='Cho phép gán liên kết'),
        ),
    ]
