# Generated by Django 5.2.7 on 2025-12-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0018_field_use_digit_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='show_amount_in_words',
            field=models.BooleanField(default=False, verbose_name='Hiển thị số thành chữ (Frontend)'),
        ),
    ]
