# Generated by Django 5.2.7 on 2026-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0019_alter_masterobjecttype_allow_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa')], db_index=True, max_length=20, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Đối tượng tác động'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian'),
        ),
    ]
