# Generated by Django 5.2.7 on 2026-02-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0020_alter_auditlog_action_alter_auditlog_target_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa'),
        ),
    ]
