# Generated by Django 5.2.7 on 2026-02-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0021_masterobject_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='loop_object_type',
            field=models.ForeignKey(blank=True, help_text='Nếu chọn, template này có thể xuất riêng từng file cho mỗi đối tượng thuộc loại này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='document_automation.masterobjecttype', verbose_name='Loại đối tượng lặp'),
        ),
    ]
