# Generated by Django 5.2.7 on 2026-03-02 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0022_documenttemplate_loop_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='editing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Đang được chỉnh sửa bởi'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='editing_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu chỉnh sửa'),
        ),
        migrations.AddField(
            model_name='masterobject',
            name='editing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_master_objects', to=settings.AUTH_USER_MODEL, verbose_name='Đang được chỉnh sửa bởi'),
        ),
        migrations.AddField(
            model_name='masterobject',
            name='editing_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu chỉnh sửa'),
        ),
    ]
