# Generated by Django 5.2.7 on 2026-03-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0023_loanprofile_editing_by_loanprofile_editing_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobject',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Bản nháp (Auto-save)'),
        ),
    ]
