# Generated by Django 5.2.7 on 2026-03-03 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0024_masterobject_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('type', models.CharField(choices=[('INFO', 'Thông tin'), ('WARN', 'Cảnh báo'), ('DANGER', 'Khẩn cấp')], default='INFO', max_length=10, verbose_name='Loại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Thông báo Quản trị',
                'verbose_name_plural': 'Thông báo Quản trị',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_stats', to='document_automation.adminnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh dấu đã đọc',
                'verbose_name_plural': 'Đánh dấu đã đọc',
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
