# Generated by Django 5.2.7 on 2026-03-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0025_adminnotification_notificationread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='AutoContract App', max_length=200, verbose_name='Tên ứng dụng')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Logo')),
                ('navbar_color', models.CharField(default='#0f172a', max_length=20, verbose_name='Màu Navbar')),
                ('brand_color', models.CharField(default='#10b981', max_length=20, verbose_name='Màu thương hiệu')),
                ('link_color', models.CharField(default='#94a3b8', max_length=20, verbose_name='Màu link')),
                ('link_hover_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Màu link khi hover')),
                ('active_link_color', models.CharField(default='#10b981', max_length=20, verbose_name='Màu link đang chọn')),
                ('active_link_bg_color', models.CharField(default='rgba(16, 185, 129, 0.1)', max_length=50, verbose_name='Màu nền link đang chọn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình Giao diện',
                'verbose_name_plural': 'Cấu hình Giao diện',
            },
        ),
    ]
