# Generated by Django 5.2.7 on 2026-03-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0026_add_system_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='Được bảo vệ (không xóa được)'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='fieldgroup',
            name='entity_type',
            field=models.CharField(choices=[('PROFILE', 'Hồ sơ'), ('PERSON', 'Cá nhân'), ('ASSET', 'Tài sản'), ('SAVINGS', 'Sổ tiết kiệm'), ('USER_EXT', 'Thông tin mở rộng Người dùng')], default='PROFILE', max_length=20, verbose_name='Đối tượng áp dụng'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('loan_profile', 'master_object', 'field', 'user')},
        ),
    ]
