# Generated by Django 5.2.7 on 2026-03-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0027_alter_fieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Chi nhánh hoặc phòng giao dịch mà người dùng này thuộc về', limit_choices_to={'object_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_members', to='document_automation.masterobject', verbose_name='Chi nhánh / Đơn vị'),
        ),
    ]
