# Generated by Django 5.2.7 on 2026-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0028_add_branch_to_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='is_protected',
        ),
        migrations.AddField(
            model_name='field',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Được bảo vệ (không xóa được)'),
        ),
    ]
