# Generated by Django 5.2.7 on 2026-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0029_add_is_system_to_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldgroup',
            name='is_protected',
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Là hệ thống (Không xóa được)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Là hệ thống (Không xóa được)'),
        ),
    ]
