# Generated by Django 5.2.7 on 2026-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0030_standardize_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='auto_save_enabled',
            field=models.BooleanField(default=True, verbose_name='Bật tự động lưu (Snapshot 2p)'),
        ),
    ]
