# Generated by Django 5.2.7 on 2026-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0031_systemconfig_auto_save_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobjecttype',
            name='allowed_relation_types',
            field=models.ManyToManyField(blank=True, help_text='Danh sách các loại đối tượng mà loại này ĐƯỢC PHÉP liên kết tới. Nếu để trống = Cho phép tất cả (Public)', related_name='allowed_by', to='document_automation.masterobjecttype', verbose_name='Whitelist liên kết (Allowed Types)'),
        ),
        migrations.AddField(
            model_name='masterobjecttype',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Nếu bật, loại đối tượng này sẽ bị ẩn khỏi tìm kiếm chung, chỉ những loại đối tượng có trong Whitelist mới thấy nhau', verbose_name='Hạn chế quyền truy cập (Restricted)'),
        ),
    ]
