# Generated by Django 5.2.7 on 2026-03-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_automation', '0032_masterobjecttype_allowed_relation_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='delete_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do xóa'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện xóa'),
        ),
    ]
